"""The Codex files carry the fields and values the Codex docs require.

Sources: https://developers.openai.com/codex/config-reference (keys, and those a
project file may not set) and https://developers.openai.com/codex/subagents
(custom agent files).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tac.adapters import charter_sha256
from tac.config import load_config
from tac.doctor import Status, hook_trust_status
from tac.sync import sync
from tac.work import Bad
from tests._syncproject import copy_project, replace_in, synced, toml

# Keys Codex ignores in a project-local .codex/config.toml.
PROJECT_IGNORED = {
    "openai_base_url",
    "chatgpt_base_url",
    "apps_mcp_product_sku",
    "model_provider",
    "model_providers",
    "notify",
    "profile",
    "profiles",
    "experimental_realtime_ws_base_url",
    "otel",
}
TOP_KEYS = {
    "sandbox_mode",
    "approval_policy",
    "sandbox_workspace_write",
    "shell_environment_policy",
    "analytics",
    "feedback",
    "agents",
}
SANDBOX_MODES = {"read-only", "workspace-write", "danger-full-access"}
# `untrusted` is no longer supported and `on-failure` is deprecated.
APPROVAL_POLICIES = {"on-request", "never"}
INHERIT = {"all", "core", "none"}
REQUIRED_AGENT_FIELDS = {"name", "description", "developer_instructions"}
AGENT_FIELDS = {*REQUIRED_AGENT_FIELDS, "model", "model_reasoning_effort"}
EFFORTS = {"low", "medium", "high", "xhigh", "max"}


@pytest.fixture
def root(tmp_path: Path) -> Path:
    return synced(tmp_path)


def test_the_project_config_sets_no_key_codex_ignores_there(root: Path) -> None:
    data = toml(root / ".codex/config.toml")
    assert set(data) <= TOP_KEYS
    assert not set(data) & PROJECT_IGNORED


def test_the_active_profile_is_rendered_as_top_level_keys(root: Path) -> None:
    data = toml(root / ".codex/config.toml")
    profile = load_config(root).profile
    assert data["sandbox_mode"] == profile.codex.sandbox_mode
    assert data["approval_policy"] == profile.codex.approval_policy
    assert data["sandbox_mode"] in SANDBOX_MODES - {"danger-full-access"}
    assert data["approval_policy"] in APPROVAL_POLICIES - {"never"}


def test_analytics_and_feedback_are_off(root: Path) -> None:
    data = toml(root / ".codex/config.toml")
    assert data["analytics"] == {"enabled": False}
    assert data["feedback"] == {"enabled": False}


def test_commands_get_no_network_and_no_secrets(root: Path) -> None:
    data = toml(root / ".codex/config.toml")
    assert data["sandbox_workspace_write"] == {"network_access": False}
    env = data["shell_environment_policy"]
    assert env["inherit"] in INHERIT
    assert env["inherit"] == load_config(root).runtime.env.codex_inherit
    assert env["ignore_default_excludes"] is False


def test_native_subagents_follow_the_profile_and_the_budget(root: Path) -> None:
    agents = toml(root / ".codex/config.toml")["agents"]
    assert agents["enabled"] is True
    assert (
        agents["max_concurrent_threads_per_session"]
        == load_config(root).knobs.teams.max_local_agents
    )


def test_native_delegation_off_removes_the_spawn_tools(tmp_path: Path) -> None:
    root = copy_project(tmp_path)
    replace_in(
        root / ".agents/config/profiles/standard.toml",
        'native_delegation = "guarded"',
        'native_delegation = "off"',
    )
    sync(root)
    assert toml(root / ".codex/config.toml")["agents"]["enabled"] is False


@pytest.mark.parametrize("value", ["untrusted", "on-failure"])
def test_an_approval_policy_codex_no_longer_takes_is_refused(
    tmp_path: Path, value: str
) -> None:
    root = copy_project(tmp_path)
    replace_in(
        root / ".agents/config/profiles/standard.toml",
        'approval_policy = "on-request"',
        f'approval_policy = "{value}"',
    )
    with pytest.raises(Bad, match="approval_policy"):
        load_config(root)


def test_the_generated_config_explains_every_key(root: Path) -> None:
    text = (root / ".codex/config.toml").read_text()
    assert text.startswith("# Generated by `tac sync`")
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line and not line.startswith(("#", "[")):
            assert lines[i - 1].startswith("#"), line


def test_the_rendered_hooks_wait_for_the_owner_s_approval(root: Path) -> None:
    # Codex runs a project hook only once approved by its hash, and keeps the
    # approvals where tac cannot read them, so the doctor names the owner's step.
    status, detail = hook_trust_status(root)
    assert status is Status.UNKNOWN
    assert ".codex/hooks.json" in detail and "/hooks" in detail


def test_every_agent_file_has_the_fields_codex_requires(root: Path) -> None:
    files = sorted((root / ".codex/agents").glob("*.toml"))
    assert files
    for path in files:
        data = toml(path)
        assert REQUIRED_AGENT_FIELDS <= set(data) <= AGENT_FIELDS, path.name
        for field in REQUIRED_AGENT_FIELDS:
            assert isinstance(data[field], str) and data[field].strip(), field
        assert data["name"] == path.stem
        assert data["model_reasoning_effort"] in EFFORTS
        assert f"# charter-sha256: {charter_sha256(root, path.stem)}" in (
            path.read_text()
        )


def test_agents_render_for_the_roles_seated_on_openai(root: Path) -> None:
    config = load_config(root)
    seated = {
        role for role, spec in config.models.roles.items() if "openai" in spec.seats()
    }
    seated |= (
        {"director"}
        if any(d.provider == "openai" for d in config.models.directors.values())
        else set()
    )
    assert {p.stem for p in (root / ".codex/agents").glob("*.toml")} == seated
    assert "chief" not in seated


def test_an_agent_carries_its_seat_and_its_charter(root: Path) -> None:
    models = toml(root / ".agents/config/models.toml")
    builder = toml(root / ".codex/agents/builder.toml")
    seat = models["roles"]["builder"]["openai"]
    assert builder["model"] == seat["model"]
    assert builder["model_reasoning_effort"] == seat["effort"]
    charter = toml(root / ".agents/config/roles/builder.toml")
    assert builder["description"] == charter["description"]
    assert charter["instructions"].strip() in builder["developer_instructions"]
    for item in charter["may_not"]:
        assert f"- {item}" in builder["developer_instructions"]


def test_the_director_takes_the_openai_seat(root: Path) -> None:
    director = toml(root / ".codex/agents/director.toml")
    seat = toml(root / ".agents/config/models.toml")["directors"]["astra"]
    assert director["model"] == seat["model"]
    assert director["model_reasoning_effort"] == seat["effort"]
