"""`tac hook run`: the full checker the stamped guard calls on each hook event.

The guard (`hooks/run.py`, stamped to `.agents/hooks/run.py`) is stdlib only and
speaks each client's hook protocol; it knows nothing about policy. This module
reads `config/hooks.toml`, runs every check wired for the client and the event,
and answers one verdict as JSON, which the guard turns into an exit code or the
client's own decision field. The answer carries where `tac` was imported from,
so the guard can refuse a checker that is not the deployed, non-editable copy.

Hooks remind and refuse early; the gate is `tac check`, the work-order checks,
CI and the ruleset (DESIGN 9).
"""

from __future__ import annotations

import fnmatch
import os
import re
from collections.abc import Callable, Iterator, Mapping
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, JsonValue

import tac
from tac import work
from tac.config import Config, load_config
from tac.draft07 import draft07
from tac.sync import generated_paths

CONTRACT = "contracts/hook-verdict.schema.json"
Client = Literal["claude", "codex"]
# The events the guard forwards, per client, as each client's docs name them.
EVENTS: Mapping[str, tuple[str, ...]] = {
    "claude": ("PreToolUse", "PostToolUse", "Stop", "SubagentStop", "SessionStart"),
    "codex": ("PreToolUse", "PostToolUse", "Stop", "SessionStart"),
}
# A subagent's stop on Claude is judged by the checks written for Stop.
CONFIGURED_AS = {"SubagentStop": "Stop"}
# Events that carry a tool_name for the matchers; the rest match only `*`.
TOOL_EVENTS = frozenset({"PreToolUse", "PostToolUse"})
# Where each tool names the file it acts on: Edit, Write, Read and NotebookEdit
# use file_path or notebook_path; Grep and Glob search under path, and Glob's
# pattern may name a file outright.
EDIT_KEYS = ("file_path", "notebook_path")
READ_KEYS = ("file_path", "notebook_path", "path", "pattern")


class Verdict(BaseModel):
    """What the checker answers the guard, once per hook event."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    verdict: Literal["allow", "deny", "remind"]
    # The hooks.toml check that decided, or empty when none fired.
    check: str
    reason: str
    # Where `tac` was imported from; the guard refuses anything outside .agents/.venv.
    module: str


def verdict_json_schema() -> dict[str, JsonValue]:
    """The verdict as JSON Schema draft-07, generated from the model."""
    return draft07(Verdict)


def module_origin() -> str:
    return os.path.realpath(tac.__file__ or "")


# ---------------------------------------------------------------- checks

# A check answers the reason it fires, or None when the call is fine.
Check = Callable[[Path, Mapping[str, Any], Config], "str | None"]


def _targets(payload: Mapping[str, Any], keys: tuple[str, ...]) -> Iterator[str]:
    given = payload.get("tool_input")
    if not isinstance(given, Mapping):
        return
    for key in keys:
        value = given.get(key)
        if isinstance(value, str) and value:
            yield value


def _absolute(raw: str, payload: Mapping[str, Any], root: Path) -> Path:
    path = Path(os.path.expanduser(raw))
    if not path.is_absolute():
        base = payload.get("cwd")
        path = (Path(base) if isinstance(base, str) and base else root) / path
    return Path(os.path.realpath(path))


def _relative(path: Path, root: Path) -> str | None:
    try:
        return path.relative_to(root.resolve()).as_posix()
    except ValueError:
        return None


def _glob_match(text: str, pattern: str) -> bool:
    """fnmatch with `**` read as `*`, since fnmatch's `*` already crosses
    folders; `dir/**` covers the folder itself too, as a search root."""
    if pattern.endswith("/**") and fnmatch.fnmatchcase(text, pattern[:-3]):
        return True
    return fnmatch.fnmatchcase(text, pattern.replace("**", "*"))


def check_generated_paths(
    root: Path, payload: Mapping[str, Any], config: Config
) -> str | None:
    """An edit to a generated file or a path the policy keeps from every agent."""
    generated = set(generated_paths(root))
    for raw in _targets(payload, EDIT_KEYS):
        rel = _relative(_absolute(raw, payload, root), root)
        if rel is None:
            continue
        if rel in generated:
            return (
                f"{rel} is generated by tac sync; change .agents/ or "
                "templates/adapters/ and run tac sync instead"
            )
        for pattern in config.policy.paths.deny_write:
            if _glob_match(rel, pattern):
                return f"{rel} is under {pattern}, which no agent writes (policy.toml)"
    return None


def _secret(path: Path, rel: str | None, pattern: str) -> bool:
    if pattern.startswith("~"):
        return _glob_match(path.as_posix(), os.path.expanduser(pattern))
    if "/" not in pattern:
        return _glob_match(path.name, pattern)
    candidates = [path.as_posix()] + ([rel] if rel else [])
    return any(
        _glob_match(c, pattern) or _glob_match(c, "*/" + pattern) for c in candidates
    )


def check_secret_read(
    root: Path, payload: Mapping[str, Any], config: Config
) -> str | None:
    """A read, search or glob that names a secret the policy keeps from agents."""
    for raw in _targets(payload, READ_KEYS):
        path = _absolute(raw, payload, root)
        rel = _relative(path, root)
        for pattern in config.policy.paths.deny_read:
            if _secret(path, rel, pattern) or _glob_match(raw, pattern):
                return f"{raw} matches {pattern}, which no agent reads (policy.toml)"
    return None


def check_owned_paths(
    _root: Path, payload: Mapping[str, Any], _config: Config
) -> str | None:
    """An edit outside what the orders on this branch own (tac work)."""
    code, why = work.hook_pre_tool(dict(payload))
    return why if code else None


def check_order(_root: Path, payload: Mapping[str, Any], _config: Config) -> str | None:
    """A stop while the order this agent worked on does not hold (tac work)."""
    code, why = work.hook_stop(dict(payload))
    return why if code else None


def check_not_yet(
    _root: Path, _payload: Mapping[str, Any], _config: Config
) -> str | None:
    """Wired, but its evidence does not exist yet: the handoff guard needs the
    runner's single-use dispatch tokens (M3, C1), and a subagent start is only
    recorded once the worker store journal exists. Until then it lets the call
    through, and the profile's native_delegation setting is what refuses."""
    return None


CHECKS: Mapping[str, Check] = {
    "generated-paths": check_generated_paths,
    "secret-read": check_secret_read,
    "owned-paths": check_owned_paths,
    "order-check": check_order,
    "handoff-guard": check_not_yet,
    "spawn-record": check_not_yet,
}


# ---------------------------------------------------------------- evaluation


def wired(matcher: str, tool: str) -> bool:
    """Whether a client matcher covers this tool: empty is not wired, `*` is
    every tool, anything else is a regular expression over the whole name, as
    Claude and Codex read their own matchers."""
    if not matcher:
        return False
    if matcher == "*":
        return True
    try:
        return re.fullmatch(matcher, tool) is not None
    except re.error:
        return False


def evaluate(
    root: Path,
    client: str,
    event: str,
    payload: Mapping[str, Any],
    config: Config | None = None,
) -> Verdict:
    """Run every check wired for this client and event. The first refusal
    decides; reminders are joined; a record never changes the answer."""
    if event not in EVENTS.get(client, ()):
        raise work.Bad(f"{client} fires no {event} the guard answers")
    config = config or load_config(root)
    as_configured = CONFIGURED_AS.get(event, event)
    tool = str(payload.get("tool_name") or "")
    reminders: list[tuple[str, str]] = []
    for name, spec in config.hooks.checks.items():
        if spec.event != as_configured or spec.kind == "record":
            continue
        matcher = spec.claude if client == "claude" else spec.codex
        if not wired(matcher, tool if event in TOOL_EVENTS else "*"):
            continue
        run = CHECKS.get(name)
        why = (
            run(root, payload, config)
            if run
            else f"no check named {name} in this tac; hooks.toml and tac disagree"
        )
        if why is None:
            continue
        if spec.kind == "deny":
            return Verdict(
                verdict="deny", check=name, reason=why, module=module_origin()
            )
        reminders.append((name, why))
    if reminders:
        return Verdict(
            verdict="remind",
            check=", ".join(n for n, _ in reminders),
            reason="\n".join(w for _, w in reminders),
            module=module_origin(),
        )
    return Verdict(verdict="allow", check="", reason="", module=module_origin())
