"""`tac sync` and `tac check`: render every harness's own files from `.agents/`,
and prove that what is committed is exactly what a render gives.

Each template under templates/adapters/<harness>/ names its output on its first
line, `{# output: <path> #}`, and that path must be one of the allowlist below,
so no template can write anywhere else. A per-role template names
`{role}` in its path and renders once per role with a seat on that harness.
Templates render in a sandboxed Jinja environment with StrictUndefined and no
loader, so a template can neither reach Python objects nor read other files.

Structured outputs are never spelt out by Jinja (design section 2.3). A data
template, named `<output>.data.j2`, renders the data as TOML; sync parses it and
serialises it with a writer, JSON for a `.json` output and TOML for a `.toml`
one, keeping the template's comments in a TOML output. Markdown is rendered as
text.

`generated.lock` records the sha256 of every input, template, the policy, the
floor and every output. `check` renders into memory and names each difference:
a missing or unexpected output, an output edited by hand, and a lock that no
longer matches its inputs.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from jinja2 import StrictUndefined, TemplateError
from jinja2.sandbox import SandboxedEnvironment

from tac import adapters, contracts, handoff, pipelines, tomlwrite
from tac.config import CONFIG_DIR, Config, load_config
from tac.standards import FLOOR_FILE
from tac.tomldoc import document
from tac.work import KNOBS_FILE, Bad

TEMPLATES_DIR = "templates/adapters"
LOCK_FILE = ".agents/generated.lock"
POLICY_FILE = f"{CONFIG_DIR}/policy.toml"
SKILLS_DIR = ".agents/skills"
CLAUDE_SKILLS_DIR = ".claude/skills"
LOCK_VERSION = 1

# Every path a template may write, per template folder. `common` renders for
# every harness; the others only while [harnesses] enforced names them.
ALLOWED: dict[str, tuple[str, ...]] = {
    "common": ("AGENTS.md",),
    "claude": ("CLAUDE.md", ".claude/settings.json", ".claude/agents/{role}.md"),
    "codex": (".codex/config.toml", ".codex/agents/{role}.toml"),
}
# Folders whose every file is generated: a file there that no template renders
# is an unexpected output.
OWNED_DIRS = (".claude/agents", ".codex/agents")
FIRST_LINE = re.compile(r"^\{#\s*output:\s*(\S+)\s*#\}\s*$")
ROLE_NAME = re.compile(r"^[a-z][a-z0-9-]*$")

NOTE = "Generated by `tac sync` from .agents/ and {template}; edit those, never this."
LOCK_HEADER = (
    "Written by `tac sync`, never by hand: the sha256 of every input, template,\n"
    "the policy, the floor and every generated output. `tac check` fails when a\n"
    "generated file or an input no longer matches what is recorded here."
)
LOCK_SECTIONS = ("inputs", "templates", "policy", "floor", "outputs")


# ---------------------------------------------------------------- templates


@dataclass(frozen=True, slots=True)
class Template:
    """One adapter template: where it lives, what it writes, and its body."""

    rel: str
    folder: str
    output: str
    body: str

    @property
    def per_role(self) -> bool:
        return "{role}" in self.output

    @property
    def structured(self) -> bool:
        return self.rel.endswith(".data.j2")


def read_template(root: Path, rel: str) -> Template:
    """A template, refused unless its first line names an allowed output."""
    text = (root / rel).read_text(encoding="utf-8")
    first, _, body = text.partition("\n")
    match = FIRST_LINE.match(first)
    if match is None:
        raise Bad(f"{rel}: the first line must be {{# output: <path> #}}")
    folder = Path(rel).relative_to(TEMPLATES_DIR).parts[0]
    output = match.group(1)
    if folder not in ALLOWED:
        raise Bad(f"{rel}: {folder} is not a harness tac renders for")
    if output not in ALLOWED[folder]:
        raise Bad(
            f"{rel}: output {output} is not on the allowlist for {folder}: "
            f"{', '.join(ALLOWED[folder])}"
        )
    template = Template(rel, folder, output, body)
    if template.output.endswith((".json", ".toml")) != template.structured:
        raise Bad(
            f"{rel}: a JSON or TOML output renders from a .data.j2 data template, "
            "and nothing else does"
        )
    return template


def templates(root: Path) -> list[Template]:
    folder = root / TEMPLATES_DIR
    if not folder.is_dir():
        raise Bad(f"{TEMPLATES_DIR}: missing")
    found = [
        read_template(root, p.relative_to(root).as_posix())
        for p in sorted(folder.rglob("*.j2"))
    ]
    outputs = [t.output for t in found]
    for dup in sorted({o for o in outputs if outputs.count(o) > 1}):
        raise Bad(f"{TEMPLATES_DIR}: two templates write {dup}")
    return found


def _toml_value(item: Any) -> str:
    return tomlwrite.value(item)


def _environment() -> SandboxedEnvironment:
    env = SandboxedEnvironment(
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["toml"] = _toml_value
    # A JSON string is a valid YAML scalar, which the agent frontmatter needs.
    env.filters["json"] = lambda item: json.dumps(item, ensure_ascii=False)
    return env


def _serialise(template: Template, output: str, text: str) -> str:
    if not template.structured:
        return text.rstrip("\n") + "\n"
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        raise Bad(f"{template.rel}: renders TOML that does not parse: {e}") from None
    if output.endswith(".json"):
        return json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    comments = {path: doc.comment for path, doc in document(text).items()}
    header = "\n".join([NOTE.format(template=template.rel), *_preamble(text)])
    return tomlwrite.dumps(data, header=header, comments=comments)


def _preamble(text: str) -> list[str]:
    """The comment block a TOML template opens with, up to its first blank line:
    what the file is, which the per-key comments cannot say."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("#"):
            break
        lines.append(stripped[1:].strip())
    return lines


# ---------------------------------------------------------------- rendering


@dataclass
class Render:
    """Everything one sync writes: output path to text, and the lock."""

    outputs: dict[str, str] = field(default_factory=dict)
    sources: dict[str, str] = field(default_factory=dict)
    lock: str = ""
    lock_data: dict[str, dict[str, str]] = field(default_factory=dict)


def _plan(config: Config, found: list[Template]) -> list[tuple[Template, str, str]]:
    """(template, output path, role or "") for every file this config renders."""
    enforced = set(config.knobs.harnesses.enforced)
    plan = []
    for template in found:
        if template.folder != "common" and template.folder not in enforced:
            continue
        if not template.per_role:
            plan.append((template, template.output, ""))
            continue
        for name in sorted(config.roles):
            if not ROLE_NAME.match(name):
                raise Bad(f"{CONFIG_DIR}/roles/{name}.toml: not a role name")
            if adapters.seat(config, name, template.folder) is not None:
                plan.append((template, template.output.format(role=name), name))
    return plan


def _context(
    config: Config, root: Path, harness: str, outputs: list[str]
) -> dict[str, Any]:
    ctx: dict[str, Any] = {"common": adapters.common(config, root, outputs)}
    if harness == "claude":
        ctx["claude"] = adapters.claude(config, root, outputs)
    elif harness == "codex":
        ctx["codex"] = adapters.codex(config, root)
    return ctx


def render(root: Path, config: Config | None = None) -> Render:
    """Every output and the lock, in memory; nothing is written."""
    config = config or load_config(root)
    found = templates(root)
    plan = _plan(config, found)
    outputs = sorted(path for _, path, _ in plan)
    env = _environment()
    result = Render()
    for template, path, role in plan:
        ctx = _context(config, root, template.folder, outputs)
        ctx["note"] = NOTE.format(template=template.rel)
        if role:
            roles = ctx[template.folder]["roles"]
            ctx["role"] = next(r for r in roles if r["name"] == role)
        try:
            text = env.from_string(template.body).render(ctx)
        except TemplateError as e:
            raise Bad(f"{template.rel}: {e.__class__.__name__}: {e}") from None
        result.outputs[path] = _serialise(template, path, text)
        result.sources[path] = template.rel
    result.lock_data = lock_data(root, found, result.outputs)
    result.lock = tomlwrite.dumps(
        {"schema_version": LOCK_VERSION, **result.lock_data}, header=LOCK_HEADER
    )
    return result


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def input_files(root: Path) -> list[str]:
    """What the renders read, besides the templates, the policy and the floor."""
    rels = [KNOBS_FILE]
    config_dir = root / CONFIG_DIR
    rels += [
        p.relative_to(root).as_posix()
        for p in sorted(config_dir.rglob("*.toml"))
        if p.relative_to(root).as_posix() != POLICY_FILE
    ]
    context = root / adapters.CONTEXT_DIR
    if context.is_dir():
        rels += [
            p.relative_to(root).as_posix()
            for p in sorted(context.rglob("*"))
            if p.is_file()
        ]
    return rels


def lock_data(
    root: Path, found: list[Template], outputs: Mapping[str, str]
) -> dict[str, dict[str, str]]:
    def hashes(rels: list[str]) -> dict[str, str]:
        return {rel: _digest((root / rel).read_bytes()) for rel in sorted(rels)}

    return {
        "inputs": hashes(input_files(root)),
        "templates": hashes([t.rel for t in found]),
        "policy": hashes([POLICY_FILE]),
        "floor": hashes([FLOOR_FILE]),
        "outputs": {
            path: _digest(text.encode("utf-8"))
            for path, text in sorted(outputs.items())
        },
    }


def read_lock(root: Path) -> dict[str, dict[str, str]] | None:
    path = root / LOCK_FILE
    if not path.is_file():
        return None
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as e:
        raise Bad(f"{LOCK_FILE}: not valid TOML: {e}") from None
    if data.get("schema_version") != LOCK_VERSION:
        raise Bad(
            f"{LOCK_FILE}: schema_version = {data.get('schema_version')!r}, "
            f"this tac reads {LOCK_VERSION}"
        )
    return {s: dict(data.get(s, {})) for s in LOCK_SECTIONS}


def locked_outputs(root: Path) -> list[str]:
    """The generated paths the committed lock lists; empty before the first sync."""
    try:
        lock = read_lock(root)
    except Bad:
        return []
    return sorted(lock["outputs"]) if lock else []


def allowed_output(rel: str) -> bool:
    """Whether some template may write `rel`: the allowlist, with `{role}` one
    role name."""
    for patterns in ALLOWED.values():
        for pattern in patterns:
            head, found, tail = pattern.partition("{role}")
            if not found:
                if rel == pattern:
                    return True
                continue
            name = rel[len(head) : len(rel) - len(tail)]
            if (
                rel.startswith(head)
                and rel.endswith(tail)
                and len(rel) > len(head) + len(tail)
                and ROLE_NAME.match(name)
            ):
                return True
    return False


def generated_paths(root: Path) -> tuple[str, ...]:
    """What any work order may touch because `tac sync` rewrites it: the lock and
    every output it lists. Only allowlisted outputs count, so a lock edited to
    name some other file widens no order."""
    return (LOCK_FILE, *(r for r in locked_outputs(root) if allowed_output(r)))


# ---------------------------------------------------------------- sync


def _write(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def sync(root: Path, *, links: bool = True) -> list[str]:
    """Write every output and the lock; remove outputs the old lock listed that
    nothing renders now. Returns what changed, as lines for the terminal."""
    config = load_config(root)
    result = render(root, config)
    changed = []
    for rel in locked_outputs(root):
        if rel not in result.outputs and (root / rel).is_file():
            (root / rel).unlink()
            changed.append(f"removed {rel}")
    for rel, text in result.outputs.items():
        if _write(root / rel, text):
            changed.append(f"wrote {rel}")
    if _write(root / LOCK_FILE, result.lock):
        changed.append(f"wrote {LOCK_FILE}")
    if links and "claude" in config.knobs.harnesses.enforced:
        changed += link_skills(root)
    return changed


def link_skills(root: Path) -> list[str]:
    """`.claude/skills/<n>` for each skill under `.agents/skills/`: a relative
    link where the platform allows one, else a copy. Never committed; a skill
    folder that is itself a link is refused, so a skill cannot point outside."""
    source = root / SKILLS_DIR
    target = root / CLAUDE_SKILLS_DIR
    if not source.is_dir():
        return []
    changed: list[str] = []
    wanted = set()
    for skill in sorted(source.iterdir()):
        if not skill.is_dir() and not skill.is_symlink():
            continue
        if skill.is_symlink():
            raise Bad(f"{SKILLS_DIR}/{skill.name}: a skill folder may not be a link")
        wanted.add(skill.name)
        dest = target / skill.name
        relative = os.path.relpath(skill, target)
        if dest.is_symlink() and os.readlink(dest) == relative:
            continue
        if dest.is_symlink() or dest.is_file():
            dest.unlink()
        elif dest.is_dir():
            shutil.rmtree(dest)
        target.mkdir(parents=True, exist_ok=True)
        try:
            dest.symlink_to(relative, target_is_directory=True)
            changed.append(f"linked {CLAUDE_SKILLS_DIR}/{skill.name}")
        except OSError:
            shutil.copytree(skill, dest)
            changed.append(f"copied {CLAUDE_SKILLS_DIR}/{skill.name}")
    if target.is_dir():
        for stale in sorted(target.iterdir()):
            if stale.name in wanted:
                continue
            if stale.is_symlink() or stale.is_file():
                stale.unlink()
            else:
                shutil.rmtree(stale)
            changed.append(f"removed {CLAUDE_SKILLS_DIR}/{stale.name}")
    return changed


# ---------------------------------------------------------------- check


def _compare_section(
    name: str, old: Mapping[str, str], new: Mapping[str, str]
) -> list[str]:
    problems = []
    for rel in sorted(set(old) | set(new)):
        if rel not in new:
            problems.append(f"{LOCK_FILE}: stale, {rel} is gone since the last sync")
        elif rel not in old:
            problems.append(f"{LOCK_FILE}: stale, {rel} is new since the last sync")
        elif old[rel] != new[rel]:
            problems.append(
                f"{LOCK_FILE}: stale, {name} {rel} changed since the last sync"
            )
    return problems


def check_tree(root: Path) -> list[str]:
    """Every way the committed files differ from a fresh render; empty is clean."""
    try:
        config = load_config(root)
        result = render(root, config)
    except Bad as e:
        return str(e).splitlines()
    problems: list[str] = []
    try:
        lock = read_lock(root)
    except Bad as e:
        lock = None
        problems.append(str(e))
    if lock is None and not problems:
        problems.append(f"{LOCK_FILE}: missing; run tac sync")
    if lock is not None:
        for section in ("inputs", "templates", "policy", "floor"):
            problems += _compare_section(
                section, lock[section], result.lock_data[section]
            )
    recorded = lock["outputs"] if lock else {}
    for rel, text in result.outputs.items():
        path = root / rel
        if not path.is_file():
            problems.append(f"{rel}: missing; run tac sync")
            continue
        on_disk = path.read_bytes()
        if on_disk == text.encode("utf-8"):
            continue
        if recorded.get(rel) == _digest(on_disk):
            problems.append(f"{rel}: out of date with its inputs; run tac sync")
        else:
            problems.append(
                f"{rel}: edited by hand; it matches neither a render nor the lock. "
                f"Edit {result.sources[rel]} or .agents/ and run tac sync"
            )
    for folder in OWNED_DIRS:
        for path in (
            sorted((root / folder).glob("*")) if (root / folder).is_dir() else []
        ):
            rel = path.relative_to(root).as_posix()
            if rel not in result.outputs:
                problems.append(f"{rel}: unexpected; no template renders it")
    for rel in sorted(set(recorded) - set(result.outputs)):
        if (root / rel).is_file():
            problems.append(f"{rel}: listed in the lock but no longer rendered")
    if lock is not None and not problems:
        current = (root / LOCK_FILE).read_text(encoding="utf-8")
        if current != result.lock:
            problems.append(f"{LOCK_FILE}: not what tac sync writes; run tac sync")
    problems += _chain_budget(config, result)
    problems += contracts.check_contracts(root)
    problems += handoff.check_templates(root)
    problems += pipelines.check_pipelines(root)
    return problems


def _chain_budget(config: Config, result: Render) -> list[str]:
    """Codex stops reading the AGENTS.md chain at 32 KiB; tac holds it under the
    profile's budget so nothing is cut off silently."""
    limit = config.profile.context.agents_md_chain_max_kb * 1024
    size = len(result.outputs.get("AGENTS.md", "").encode("utf-8"))
    if size > limit:
        return [
            f"AGENTS.md: {size} bytes, over the {limit} byte budget "
            f"(profile context.agents_md_chain_max_kb); shorten "
            f"{adapters.BRIEF_FILE}"
        ]
    return []


def staged_tree(root: Path, into: Path) -> Path:
    """The index as a folder: what a commit would hold, not the working tree."""
    done = subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "checkout-index",
            "--all",
            "--force",
            f"--prefix={into}/",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if done.returncode != 0:
        raise Bad(f"git checkout-index: {done.stderr.strip()[:300]}")
    return into


def check_staged(root: Path) -> list[str]:
    with tempfile.TemporaryDirectory(prefix="tac-staged-") as tmp:
        return check_tree(staged_tree(root, Path(tmp)))
